import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/Sidebar";
import Header from "@/components/header/Header";
import Provider from "./provider";
import { ThemeSwitcher } from "@/components/ThemeSwitcher";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn("dark:bg-slate-900 dark:text-white", inter.className)}
      >
        <Provider>
          <Sidebar />
          <div className="ml-64 p-6">
            <Header />
            <main className="mt-8">{children}</main>
          </div>
          <ThemeSwitcher />
        </Provider>
      </body>
    </html>
  );
}
